sudo: required
language: generic
services:
 - docker
 - redis-server
 - memcached

env:
  matrix:
   - HHVM_VERSION=4.0.0
   - HHVM_VERSION=4.0.1
   - HHVM_VERSION=4.0.2
   - HHVM_VERSION=4.0.3
   - HHVM_VERSION=4.1.0
   - HHVM_VERSION=latest
install:
 - docker pull hhvm/hhvm:$HHVM_VERSION
 - docker images
script:
 - docker run --name hhvm -td hhvm/hhvm:$HHVM_VERSION
 - docker exec -it hhvm /bin/bash -c "apt-get update && apt-get -y upgrade"
 - docker exec -it hhvm /bin/bash -c "apt-get install memcached"
 - docker exec -it hhvm /bin/bash -c "apt-get install redis-server"
 - docker exec -it hhvm rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh

