sudo: required
language: generic
services:
 - docker
env:
  matrix:
   - HHVM_VERSION=4.0.0
   - HHVM_VERSION=4.0.1
   - HHVM_VERSION=4.0.2
   - HHVM_VERSION=4.0.3
   - HHVM_VERSION=latest
install:
 - docker pull hhvm/hhvm:$HHVM_VERSION
 - docker pull redis:5.0-alpine
script:
 - docker network create testing-network
 - docker run --name redis --network testing-network
 - docker run --name hhvm --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
