version: '3'
services:
  hhvm:
    build:
      context: ./docker/hhvm
      args:
        hhvmversion: ${HHVM_VERSION}
    volumes:
      - .:/var/source
    command: hhvm --mode server -vServer.AllowRunAsRoot=1 
    restart: always
    tty: true
  redis:
    image: redis:4-alpine3.8
    ports:
    - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
    - "11211:11211"
