version: '3'
services:
  hhvm:
    build:
      context: ./docker/hhvm
      args:
        hhvmversion: ${HHVM_VERSION}
    volumes:
      - .:/var/source
    command: hhvm --mode server -vServer.AllowRunAsRoot=1 
    restart: always
    tty: true
  memcached:
    image: memcached:latest
    ports:
    - "31211:11211"
